# Generated by Django 2.2.5 on 2020-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockAPIData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
