# Generated by Django 2.2.5 on 2020-04-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockAPIData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='resourcesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='stockAPI.resourcesData')),
            ],
        ),
    ]
